version: '3.8'
services:
  webui:
    volumes:
      - ./trades/:/app/trades/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BloombergTradeFeed;User=sa;Password=BVPay84WtygUVn; 
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "BVPay84WtygUVn"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
